### ISSUE TITLE
Mais infos

### ISSUE THREAD

**Issue by HelioCampos** [tschope/it-dublin-faq#1]
Oi,

Pode dar mais informações sobre os seguintes assuntos:
1) Sobre comida:
a) Você comentou que a comida custa uns €$ 150.00 mas esse valor é por 1 refeição, por semana ou por mês?
b) Quanto você gasta no supermercado pra uma pessoa no mês?
2) Sobre energia:
a) Quanto custa o Watt hora por ai?
b) A calefação das casas consome muito?
c) Vocês deixam a calefação ligada o dia todo? Não é perigoso?
3) Sobre água:
a) Quanto custa o metro cúbico de água para a casa ai?
b) Tomam banho todos os dias ou isso dá aqueles problemas de pele?
c) A água da torneira é potável?
d) Quanto custa o galão de água?

Abs,

**Comment by tschope** [comment]
E ai Man. Cara, vamos lá. Atualizei o FAQ com algumas de suas questões relevantes, outras vou responder aqui:

Sobre comida:
a) Você comentou que a comida custa uns €$ 150.00 mas esse valor é por 1 refeição, por semana ou por mês? 
- Mes pessoa. Mas add no FAQ valor de restaurantes e MC. Acredito que se você olhar esse site aqui terá mais exemplos interessantes: https://www.numbeo.com/cost-of-living/in/Dublin

b) Quanto você gasta no supermercado pra uma pessoa no mês? Item acima
Sobre energia:
a) Quanto custa o Watt hora por ai? MUITO variável, tem Landrlord FDP que poem energia pré paga e ganha em cima de você com isso, é uma merda. Aqui é uma doidera isso, tem 20 mil operadoras e planos então, mais barato é verificando esse site aqui: https://switcher.ie/
b) A calefação das casas consome muito? Um pouco, gás é mais caro que energia eletrica.
c) Vocês deixam a calefação ligada o dia todo? Não é perigoso? Não deixo 24h, apesar de existir uns Smarts tanto faz que faz isso, controla a temperatura para quando você não está em casa para menos, uns 10-15 graus e quando você vai pra casa você aumenta. Não é meu caso, eu ligo, alternando, umas 2-3 horas por dia no inverno. As casas aqui tem paredes que costumam deixar o ambiente quente por um tempo, então não ligo o aquecedor mais que isso não.

Sobre água:
a) Quanto custa o metro cúbico de água para a casa ai? Não faço ideia, mas cara, é tipo de graça. Procure sobre, não se cobra agua aqui. Eu não pago.
b) Tomam banho todos os dias ou isso dá aqueles problemas de pele? Não, 1-2 banhos dia. Normal.
c) A água da torneira é potável? Sim, mas uso filtro mesmo assim.
d) Quanto custa o galão de água? Não sei. 

Espero ter ajudado. Abs
